[package]
name = "ding-king"
version = "0.1.0"
authors = ["sean@policarp.io <sean@policarp.io>"]
edition = "2018"

[dependencies]
regex = "1.1.6"
serde = { version = "1.0.91", features = ["derive"]}
serde_json = "1.0.39"
reqwest = "0.9.17"
clap = "2.33.0"
